config/routes.rb
TestM::Application.routes.draw do

  devise_for :users
  resources :users

  resources :roles
  resources :groups
  resources :uploaded_files
  resources :events

  root to: 'static_pages#home'

  match '/admin', to: 'admin#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name

  validates :name,  presence: true, length: { maximum: 50 }

  has_many :users
end

app/controllers/groups_controller.rb
# -*- encoding : utf-8 -*-
class GroupsController < ApplicationController

  before_filter :authenticate_user!, :check_if_role
  before_filter :check_if_admin, except: [:index, :show]
  before_filter :check_if_builtin,  only: [:edit, :update, :destroy]
  before_filter :find_group,  only: [:show]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
  end

  def edit
  end

  def update
    if @group.update_attributes(params[:group])
      flash[:success] = "Группа успешно обновлена"
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:success] = "Группа успешно создана"
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Группа удалена."
    redirect_to groups_path
  end

  private
    def find_group
      @group = Group.where(id: params[:id]).first
      render_404 unless @group 
    end
    
    def check_if_builtin
      find_group
      render_403 unless @group.builtin == 0
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h2>Редактирование группы</h2>
<%= form_for (@group) do |f| %>
  <div>Наименование<br />
    <%= f.text_field :name, :autofocus => true %></div>
  <div><%= f.submit "Сохранить", class: "btn btn-large btn-primary" %></div>
<% end %>

app/views/groups/index.html.erb
<% provide(:title, 'Группы') %>

<h3>Группы</h3>
<div>
<table class="table table-hover">
  <thead><tr>
    <th>Наименование</th>
    <th></th>
  </tr></thead>
  <tbody>
  <% for group in @groups %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td>
          <% if admin?(current_user) && group.builtin == 0 %>
            <p class="pull-right"><%= link_to 'Редактировать', edit_group_path(group) %>
              &nbsp;|&nbsp;
              <%= link_to "Удалить", group, method: :delete, data: { confirm: "Вы уверены, что хотите удалить группу #{group.name}?" } %>
            </p>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>
<% if admin?(current_user) %>
<p> <%= button_to "Новая группа", new_group_path, method: :get, class: "btn btn-large" %></p>
<% end %>

app/views/groups/new.html.erb
<h2>Создание группы</h2>
<%= form_for (@group) do |f| %>
  <div>Наименование<br />
    <%= f.text_field :name, :autofocus => true %></div>
  <div><%= f.submit "Сохранить", class: "btn btn-large btn-primary" %></div>
<% end %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>

  <h1>
    <%= @group.name %>
  </h1>