config/routes.rb
TestM::Application.routes.draw do

  devise_for :users
  resources :users

  resources :roles
  resources :groups
  resources :uploaded_files
  resources :events

  root to: 'static_pages#home'

  match '/admin', to: 'admin#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  validates :name,  presence: true, length: { maximum: 50 }

  has_many :users

end

app/controllers/roles_controller.rb
# -*- encoding : utf-8 -*-
class RolesController < ApplicationController
  before_filter :authenticate_user!, :check_if_role
  before_filter :check_if_admin
  before_filter :check_if_builtin,  only: [:edit, :update, :destroy]
  before_filter :find_role,  only: [:show]

  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def show
  end

  def edit  
  end

  def update
    if @role.update_attributes(params[:role])
      flash[:success] = "Роль успешно обновлена"
      redirect_to roles_path
    else
      render 'edit'
    end
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      flash[:success] = "Роль успешно создана"
      redirect_to roles_path
    else
      render 'new'
    end
  end

  def destroy
    Role.find(params[:id]).destroy
    flash[:success] = "Роль удалена."
    redirect_to roles_path
  end

  private
    def find_role
      @role = Role.where(id: params[:id]).first
      render_404 unless @role       
    end
    
    def check_if_builtin
      find_role
      render_403 unless @role.builtin == 0
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/edit.html.erb
<h2>Редактирование роли</h2>
<%= form_for (@role) do |f| %>
  <div>Наименование<br />
    <%= f.text_field :name, :autofocus => true %></div>
  <div><%= f.submit "Сохранить", class: "btn btn-large btn-primary" %></div>
<% end %>

app/views/roles/index.html.erb
<% provide(:title, 'Роли') %>

<h3>Роли</h3>
<div>
<table class="table table-hover">
  <thead><tr>
    <th>Наименование</th>
    <th></th>
  </tr></thead>
  <tbody>
  <% for role in @roles %>
      <tr>
        <td><%= link_to role.name, role %></td>
        <td>
          <% if role.builtin == 0 %>
            <p class="pull-right"><%= link_to 'Редактировать', edit_role_path(role) %>
              &nbsp;|&nbsp;
              <%= link_to "Удалить", role, method: :delete, data: { confirm: "Вы уверены, что хотите удалить #{role.name}?" } %>
            </p>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>
<p> <%= button_to "Новая роль", new_role_path, method: :get, class: "btn btn-large" %></p>

app/views/roles/new.html.erb
<h2>Создание роли</h2>
<%= form_for (@role) do |f| %>
  <div>Наименование<br />
    <%= f.text_field :name, :autofocus => true %></div>
  <div><%= f.submit "Сохранить", class: "btn btn-large btn-primary" %></div>
<% end %>

app/views/roles/show.html.erb
<% provide(:title, @role.name) %>
<h1>
  <%= @role.name %>
</h1>