config/routes.rb
TestM::Application.routes.draw do

  devise_for :users
  resources :users

  resources :roles
  resources :groups
  resources :uploaded_files
  resources :events

  root to: 'static_pages#home'

  match '/admin', to: 'admin#index'

end

app/views/layouts/_footer.html.erb
<footer id="footer">
    <div class="navbar-fixed-bottom row-fluid">
      <div class="navbar-inner">
        <div class="container">
            <%= link_to "My Site", "http://ormus2002-test-m.heroku.com" %>
            Created by Ormus
        </div>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Пример", root_path, id: "logo", class: "brand" %>
      <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right" id="main-menu-right">
          <% if user_signed_in? %>
            <% if admin?(current_user) %>
              <li><%= link_to "Администрирование", '/admin' %></li>
            <% else %>
              <li><%= link_to "Календарь", events_path %></li>
              <li><%= link_to "Файлы", uploaded_files_path %></li>
              <li><%= link_to "Группы", groups_path %></li>
              <li><%= link_to "Пользователи", users_path %></li>
            <% end %>
          <% end %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Стиль<b class="caret"></b></a>
              <ul id="sheetswitch" class="dropdown-menu">
                <li><a class='swatch' name='cerulian'>Cerulian</a></li>
                <li><a class='swatch' name='cosmo'>Cosmo</a></li>
                <li><a class='swatch' name='flatly'>Flatly</a></li>
              </ul>
          </li>
          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Профиль", user_path(current_user) %></li>
                  <li><%= link_to "Учетная запись", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Выход", destroy_user_session_path, :method=>'delete' %>
                  </li>
                </ul>
            </li>
          <% else %>
            <li><%= link_to "Войти", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <link href="/styles/bootstrap.min_cerulian.css?body=1" class="switch" media="all" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <% if user_signed_in? && admin?(current_user)%>
          <div class="span2">
            <%= render 'shared/menu' %>
          </div>
          <div class="span10">
        <% else %>
          <div class="container">
        <% end %>

        <% flash.each do |type, message| %>
          <div class="alert <%= bootstrap_class_for(type) %> fade in">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
        <% end %>

        <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>